### ISSUE TITLE
java.lang.NoSuchMethodError: io.opentelemetry.sdk.trace.data.SpanData.getInstrumentationScopeInfo

### ISSUE THREAD

**Issue by Maikels** [avioconsulting/mule-opentelemetry-module#50]
Hello,

When upgrading the opentelemetry version to 1.18.0 to support OtlpHttpSpanExporter 'setClientTls' combined with 'setTrustedCertificates'

I keep getting following in mule app:

org.mule.runtime.core.internal.context.notification.Policy: NotificationListener MulePipelineMessageNotificationListener@4fa4d75f was unable to fire notification PipelineMessageNotification{action=pipeline process complete, resourceId=testFlow, serverId=BEDGBWN10I20402..test, timestamp=1663328140557} due to an exception: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: io.opentelemetry.sdk.trace.data.SpanData.getInstrumentationScopeInfo()Lio/opentelemetry/sdk/common/InstrumentationScopeInfo;.

While remote debugging I saw this happening because of this method (in ResourceSpansMarshaler - called when trying to end a span):
  private static Map<Resource, Map<InstrumentationScopeInfo, List<SpanMarshaler>>>
      groupByResourceAndScope(Collection<SpanData> spanDataList) {
    return MarshalerUtil.groupByResourceAndScope(
        spanDataList,
        // TODO(anuraaga): Replace with an internal SdkData type of interface that exposes these
        // two.
        SpanData::getResource,
        SpanData::getInstrumentationScopeInfo,
        SpanMarshaler::create);
  }

In particular 'getInstrumentationScopeInfo'

I'm not exactly sure why this is throwing that error as all dependencies are on 1.18.0

**Comment by manikmagar** [comment]
Thank you @Maikels for raising this. Just curious, how are you upgrading the dependency version - in this module or in your mule application?

**Comment by Maikels** [comment]
@manikmagar Hi!

I did clone this repo local and updated the otel version in the project, I need the setTrustedCertificates function and it is only available since 1.13.0.
Then just installed it locally and used the updated version in my mule project

**Comment by manikmagar** [comment]
@Maikels We have [just released v1.1.0](https://github.com/avioconsulting/mule-opentelemetry-module/releases/tag/v1.1.0) that includes upgrading OTEL to 1.19.0, along with other features. You shouldn't need to modify module for setting TLS and can just set the appropriate environment variables on your runtime for it. See [SDK Variables](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters) here.
If it doesn't work, please provide more details on how are you configuring it in your mule app and system level. Hope this helps.

**Comment by Maikels** [comment]
Thank you for getting back to me @manikmagar  ! Exactly what I needed, thanks!
